name: 'build and push image'

inputs:
  jobs-json:
    required: true

runs:
  using: "composite"
  steps:
    - name: checks
      shell: bash
      run: |
        tee needs.json <<< '${{ needs }}'
        cat needs.json