name: Preflight

inputs:
  jobs-json:
    required: true

runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v4

    - id: current-file
      shell: bash
      run: |
        echo "current-workflow-file=$(echo ${{ github.workflow_ref }} | sed -nE "s/.*(\.github\/workflows\/[a-zA-Z0-9_-]*\.y[a]?ml)@refs.*/\1/p")" >> $GITHUB_OUTPUT
        echo "current-action-dir=$(echo ${{ github.action_path }}    | sed -nE "s/.*(\.github\/actions\/[a-zA-Z0-9_-]*)/\1/p")" >> $GITHUB_OUTPUT

    - name: Get all test, doc and src files that have changed
      id: changed-files-yaml
      uses: tj-actions/changed-files@v45
      with:
        files_yaml: |
          doc:
            - '**.md'
          rust:
            - '**.rs'
          current-workflow:
            - '${{ steps.current-file.outputs.current-workflow-file }}'
            - '${{ steps.current-file.outputs.current-action-dir }}/*'
          test:
            - '**.md'
            - '**.rs'

    - name: log
      shell: bash
      run: |
        echo "action dir: ${{ steps.current-file.outputs.current-action-dir }}"
        echo "wf file: ${{ steps.current-file.outputs.current-workflow-file }}"
        echo "Modified: ${{ steps.changed-files-yaml.outputs.modified_keys }}"
