name: Preflight

on:
  push:
  pull_request:

jobs:

  final-job:
    runs-on: ubuntu-latest
    if: always() && !cancelled()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: preflight custom action
        uses: ./.github/actions/preflight