name: Preflight

on:
  push:
  pull_request:

jobs:

  final-job:
    runs-on: ubuntu-latest
    if: always() && !cancelled()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: preflight custom action
        id: preflight
        uses: ./.github/actions/preflight

      - name: preflight log
        run: |
          echo "rust: ${{ steps.preflight.outputs.changes_rust }}"
          echo "current-workflow: ${{ steps.preflight.outputs.changes_currentWorkflow }}"