name: default workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  
  #
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo "first step"
      - run: echo "secret variable ${{ secrets.SOME_TEST_SECRET }}"