name: Tests success
on:
    workflow_run:
      workflows: [Run Tests Fail]
      types:
        - completed


jobs:
  result:
    runs-on: ubuntu-latest
    steps:
      - name: success
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: exit 0
      - name: fail
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: exit 1       